### ISSUE TITLE
Processed killed when using random

### ISSUE THREAD

**Issue by madprops** [PMunch/nim-playground#9]
Hi, the following code doesn't seem to work for some reason

```
import std/random
var rng = initRand(100)
echo rng.rand(5)
```

```
Hint: used config file '/playground/nim/config/nim.cfg' [Conf]
Hint: used config file '/playground/nim/config/config.nims' [Conf]
................
Hint: gcc -c  -w -fmax-errors=3   -I/playground/nim/lib -I/usercode -o /usercode/nimcache/stdlib_assertions.nim.c.o /usercode/nimcache/stdlib_assertions.nim.c [Exec]
Killed
```

I also got a similar error with a larger code: https://pastebin.com/rT5HxvCW

**Comment by PMunch** [comment]
After some issues with the server running out of memory I clamped down on how much memory each container got to use. Apparently I went in a bit too aggressive. I've increased the amount now and it seems to work, but please respond to this issue if you find similar snippets that fails.
